import type { FlowGraph } from './types';

function mobileFlow(platform: 'android' | 'ios'): FlowGraph {
  const isAndroid = platform === 'android';
  const host = isAndroid ? 'http://10.0.2.2:4000/api/v1' : 'http://127.0.0.1:4000/api/v1';
  const hostLabel = isAndroid ? 'Android emulator host' : 'iOS simulator host';

  return {
    platform,
    title: isAndroid ? 'Android application flows' : 'iOS application flows',
    subtitle: `Same Expo React Native tree as the other mobile OS. Topology matches; the platform fork is the API base (${host}). Override with EXPO_PUBLIC_API_BASE_URL.`,
    nodes: [
      {
        id: `${platform}-login`,
        label: 'Login',
        layer: 'ui',
        kind: 'screen',
        summary: 'Demo + federated sign-in',
        constructs: `surface=mobile; opens IdP in browser.`,
        transmits: 'api.login or deep link to auth/callback.',
        files: ['mobile/app/login.tsx'],
        apis: ['api.login', "POST /auth/login { surface: 'mobile' }"],
        screenshotHint: 'Capture demo login + Try provider.',
        x: 40,
        y: 80,
      },
      {
        id: `${platform}-callback`,
        label: 'Auth callback',
        layer: 'ui',
        kind: 'screen',
        summary: '100x://auth/callback',
        constructs: 'Deep-link code/state from IdP.',
        transmits: 'api.federatedExchange → SecureStore session.',
        files: ['mobile/app/auth/callback.tsx'],
        apis: ['api.federatedExchange'],
        x: 40,
        y: 220,
      },
      {
        id: `${platform}-onboarding`,
        label: 'Local onboarding',
        layer: 'ui',
        kind: 'screen',
        summary: 'Device how-it-works (not server profile)',
        constructs: 'Local flag in SecureStore/AsyncStorage.',
        transmits: 'No putOnboarding — connections stay on web.',
        files: ['mobile/app/onboarding.tsx', 'mobile/src/onboarding.ts'],
        screenshotHint: 'Show the “setup on web” callout.',
        x: 40,
        y: 360,
      },
      {
        id: `${platform}-triage`,
        label: 'Triage tab',
        layer: 'ui',
        kind: 'screen',
        summary: 'Default post-login queue',
        constructs: 'triagePending work items + boards.',
        transmits: 'listWorkItems → triageWorkItem → job.',
        files: ['mobile/app/(tabs)/triage.tsx'],
        apis: ['api.listWorkItems', 'api.triageWorkItem'],
        screenshotHint: 'Best screenshot for mobile AI-first UX.',
        x: 280,
        y: 80,
      },
      {
        id: `${platform}-jobs`,
        label: 'AI Jobs tab',
        layer: 'ui',
        kind: 'screen',
        summary: 'Running / blocked / ready jobs',
        constructs: 'Jobs joined with work items + stats.',
        transmits: 'listJobs + listWorkItems + listBoards.',
        files: ['mobile/app/(tabs)/jobs.tsx'],
        apis: ['api.listJobs', 'api.listWorkItems'],
        x: 280,
        y: 220,
      },
      {
        id: `${platform}-ticket`,
        label: 'Ticket detail',
        layer: 'ui',
        kind: 'screen',
        summary: '/ticket/[id]',
        constructs: 'Work item + job + audit timeline.',
        transmits: 'getWorkItem, getJob, triage, assignee.',
        files: ['mobile/app/ticket/[id].tsx'],
        apis: ['api.getWorkItem', 'api.getJob', 'api.listAuditEvents'],
        x: 280,
        y: 360,
      },
      {
        id: `${platform}-approvals`,
        label: 'Approvals tab',
        layer: 'ui',
        kind: 'screen',
        summary: 'Decide pending gates',
        constructs: 'Approval rows with action metadata.',
        transmits: 'listApprovals → decideApproval.',
        files: ['mobile/app/(tabs)/approvals.tsx'],
        apis: ['api.listApprovals', 'api.decideApproval'],
        x: 520,
        y: 80,
      },
      {
        id: `${platform}-pii`,
        label: 'PII tab',
        layer: 'ui',
        kind: 'screen',
        summary: 'blocked_pii work items',
        constructs: 'Filters aiStatus=blocked_pii + job.',
        transmits: 'requestPiiAccess → creates approval.',
        files: ['mobile/app/(tabs)/pii.tsx'],
        apis: ['api.listWorkItems', 'api.requestPiiAccess'],
        x: 520,
        y: 220,
      },
      {
        id: `${platform}-account`,
        label: 'Account tab',
        layer: 'ui',
        kind: 'screen',
        summary: 'Status + read-only MCP',
        constructs: 'me + stats + boards + connections list.',
        transmits: 'No connect/disconnect — setup is web.',
        files: ['mobile/app/(tabs)/account.tsx'],
        apis: ['api.me', 'api.listMcpConnections'],
        x: 520,
        y: 360,
      },
      {
        id: `${platform}-session`,
        label: 'SessionProvider',
        layer: 'client',
        kind: 'session',
        summary: 'SecureStore → AsyncStorage fallback',
        constructs: 'Persists Bearer token on device.',
        transmits: 'Authorization header on every call.',
        files: ['mobile/src/session.tsx', 'mobile/app/_layout.tsx'],
        x: 760,
        y: 140,
      },
      {
        id: `${platform}-api-client`,
        label: 'mobile/src/api.ts',
        layer: 'client',
        kind: 'client',
        summary: 'Mobile API subset',
        constructs: 'Absolute base URL; smaller method surface.',
        transmits: host,
        files: ['mobile/src/api.ts', 'mobile/.env.example'],
        x: 760,
        y: 320,
      },
      {
        id: `${platform}-host`,
        label: hostLabel,
        layer: 'api',
        kind: 'platform',
        summary: host,
        constructs: isAndroid
          ? '10.0.2.2 maps emulator → host machine localhost.'
          : '127.0.0.1 reaches backend on the Mac running Simulator.',
        transmits: 'Same REST contract as web /api/v1.',
        files: ['mobile/src/api.ts'],
        screenshotHint: 'Include this node when debugging “API unreachable”.',
        x: 760,
        y: 480,
      },
      {
        id: `${platform}-http`,
        label: 'HTTP /api/v1',
        layer: 'api',
        kind: 'endpoint',
        summary: 'Shared backend routes',
        constructs: 'Auth middleware + JSON handlers.',
        transmits: 'routes.ts → store / orchestrator.',
        files: ['backend/src/routes.ts', 'backend/src/auth.ts'],
        x: 1000,
        y: 220,
      },
      {
        id: `${platform}-store`,
        label: 'Store',
        layer: 'backend',
        kind: 'store',
        summary: 'Same store as web',
        constructs: 'jobs, workItems, approvals, policies.',
        transmits: 'Shared with web clients in one process.',
        files: ['backend/src/store.ts'],
        x: 1240,
        y: 140,
      },
      {
        id: `${platform}-orchestrator`,
        label: 'Orchestrator',
        layer: 'runtime',
        kind: 'pipeline',
        summary: 'Triage → job pipeline',
        constructs: 'createJob from mobile triage decision.',
        transmits: 'model runner + MCP + board connectors.',
        files: ['backend/src/orchestrator.ts'],
        x: 1240,
        y: 320,
      },
      {
        id: `${platform}-model`,
        label: 'Model runner',
        layer: 'runtime',
        kind: 'pipeline',
        summary: 'No mobile Models UI',
        constructs: 'Runtime prefs authored on web governance.',
        transmits: 'Job updates visible in Jobs / Ticket tabs.',
        files: ['backend/src/runners/model.ts'],
        x: 1240,
        y: 480,
      },
      {
        id: `${platform}-web-bridge`,
        label: 'Web Connections',
        layer: 'ui',
        kind: 'screen',
        summary: 'Cross-platform setup handoff',
        constructs: 'MCP connect/OAuth only on web.',
        transmits: 'Account tab reads connections after web setup.',
        files: ['web/src/pages/Connections.tsx'],
        screenshotHint: 'Pair with Account tab to show the handoff.',
        x: 520,
        y: 500,
      },
    ],
    edges: [
      { id: `${platform}-e1`, from: `${platform}-login`, to: `${platform}-session`, label: 'token', primary: true },
      { id: `${platform}-e2`, from: `${platform}-callback`, to: `${platform}-session`, label: 'exchange', primary: true },
      { id: `${platform}-e3`, from: `${platform}-login`, to: `${platform}-callback`, label: 'federated' },
      { id: `${platform}-e4`, from: `${platform}-session`, to: `${platform}-api-client`, label: 'Bearer', primary: true },
      { id: `${platform}-e5`, from: `${platform}-onboarding`, to: `${platform}-triage`, primary: true },
      { id: `${platform}-e6`, from: `${platform}-triage`, to: `${platform}-api-client`, label: 'triage', primary: true },
      { id: `${platform}-e7`, from: `${platform}-jobs`, to: `${platform}-api-client`, primary: true },
      { id: `${platform}-e8`, from: `${platform}-ticket`, to: `${platform}-api-client` },
      { id: `${platform}-e9`, from: `${platform}-approvals`, to: `${platform}-api-client` },
      { id: `${platform}-e10`, from: `${platform}-pii`, to: `${platform}-api-client` },
      { id: `${platform}-e11`, from: `${platform}-account`, to: `${platform}-api-client` },
      { id: `${platform}-e12`, from: `${platform}-api-client`, to: `${platform}-host`, primary: true },
      { id: `${platform}-e13`, from: `${platform}-host`, to: `${platform}-http`, primary: true },
      { id: `${platform}-e14`, from: `${platform}-http`, to: `${platform}-store`, primary: true },
      { id: `${platform}-e15`, from: `${platform}-http`, to: `${platform}-orchestrator`, label: 'aiFirst', primary: true },
      { id: `${platform}-e16`, from: `${platform}-orchestrator`, to: `${platform}-model`, primary: true },
      { id: `${platform}-e17`, from: `${platform}-model`, to: `${platform}-store`, label: 'job status', primary: true },
      { id: `${platform}-e18`, from: `${platform}-triage`, to: `${platform}-ticket`, label: 'open' },
      { id: `${platform}-e19`, from: `${platform}-jobs`, to: `${platform}-ticket`, label: 'open' },
      { id: `${platform}-e20`, from: `${platform}-web-bridge`, to: `${platform}-account`, label: 'MCP read' },
      { id: `${platform}-e21`, from: `${platform}-pii`, to: `${platform}-approvals`, label: 'request access' },
    ],
  };
}

export const ANDROID_FLOW = mobileFlow('android');
export const IOS_FLOW = mobileFlow('ios');
