import type { FlowGraph } from './types';

/** Interactive map of the web app: UI → client → API → store → runtime. */
export const WEB_FLOW: FlowGraph = {
  platform: 'web',
  title: 'Web application flows',
  subtitle:
    'How screens build payloads, call /api/v1, and land in store + orchestrator. Click a node, zoom in, screenshot, then ask for a module walkthrough.',
  nodes: [
    {
      id: 'w-login',
      label: 'Login / Signup',
      layer: 'ui',
      kind: 'screen',
      summary: 'Demo login + federated IdP entry',
      constructs: 'Email/password or provider choice; surface=web.',
      transmits: 'POST /auth/login or redirect to IdP → AuthCallback.',
      files: ['web/src/pages/Login.tsx', 'web/src/pages/Signup.tsx'],
      apis: ['api.login', 'POST /auth/login'],
      screenshotHint: 'Capture the login card + provider buttons.',
      x: 40,
      y: 80,
    },
    {
      id: 'w-callback',
      label: 'Auth callback',
      layer: 'ui',
      kind: 'screen',
      summary: 'OIDC code exchange',
      constructs: 'Reads code/state from URL query.',
      transmits: 'api.federatedExchange → writes demo session.',
      files: ['web/src/pages/AuthCallback.tsx'],
      apis: ['api.federatedExchange', 'POST /auth/federated/exchange'],
      x: 40,
      y: 220,
    },
    {
      id: 'w-workspace',
      label: 'Workspace gate',
      layer: 'ui',
      kind: 'gate',
      summary: 'Company / workspace bootstrap',
      constructs: 'Ensures org context before onboarding.',
      transmits: 'Navigates to /onboarding or /home.',
      files: ['web/src/pages/WorkspaceGate.tsx'],
      x: 40,
      y: 360,
    },
    {
      id: 'w-onboarding',
      label: 'Onboarding',
      layer: 'ui',
      kind: 'screen',
      summary: 'Intent, connections, environments',
      constructs: 'Multi-step profile + env preferences.',
      transmits: 'api.ensureEnvironments + api.putOnboarding.',
      files: ['web/src/pages/Onboarding.tsx', 'web/src/components/onboarding/'],
      apis: ['api.putOnboarding', 'api.ensureEnvironments'],
      screenshotHint: 'Screenshot the step that feels wrong.',
      x: 40,
      y: 500,
    },
    {
      id: 'w-home',
      label: 'Home',
      layer: 'ui',
      kind: 'screen',
      summary: 'Connection-aware widgets',
      constructs: 'Widgets from MCP boards + messaging.',
      transmits: 'listMcpConnections, listWorkItems, Slack channels.',
      files: ['web/src/pages/WorkspaceHome.tsx', 'web/src/components/home/'],
      apis: ['api.listMcpConnections', 'api.listWorkItems'],
      x: 280,
      y: 80,
    },
    {
      id: 'w-triage',
      label: 'Triage',
      layer: 'ui',
      kind: 'screen',
      summary: 'Swipe / decide AI-first queue',
      constructs: 'Work items with triagePending + board meta.',
      transmits: 'api.triageWorkItem → creates job pipeline.',
      files: ['web/src/pages/Triage.tsx'],
      apis: ['api.listWorkItems', 'api.triageWorkItem'],
      screenshotHint: 'Best place to show AI-first decision UI.',
      x: 280,
      y: 220,
    },
    {
      id: 'w-work',
      label: 'Project work',
      layer: 'ui',
      kind: 'screen',
      summary: 'Board-scoped work list',
      constructs: 'Filters by projectId + board.',
      transmits: 'listBoards + listWorkItems({projectId}).',
      files: ['web/src/pages/ProjectWork.tsx', 'web/src/components/work/'],
      apis: ['api.listBoards', 'api.listWorkItems'],
      x: 280,
      y: 360,
    },
    {
      id: 'w-task',
      label: 'Task detail',
      layer: 'ui',
      kind: 'screen',
      summary: 'Work item + job + audit',
      constructs: 'Merges workItem, job, audit trail.',
      transmits: 'getWorkItem, getJob, listAuditEvents, triage.',
      files: ['web/src/pages/TaskDetail.tsx'],
      apis: ['api.getWorkItem', 'api.getJob', 'api.listAuditEvents'],
      x: 280,
      y: 500,
    },
    {
      id: 'w-approvals',
      label: 'Approvals',
      layer: 'ui',
      kind: 'screen',
      summary: 'Human gates for AI actions',
      constructs: 'Pending approvals list + decision payload.',
      transmits: 'listApprovals → decideApproval.',
      files: ['web/src/pages/Approvals.tsx'],
      apis: ['api.listApprovals', 'api.decideApproval'],
      x: 520,
      y: 80,
    },
    {
      id: 'w-pii',
      label: 'PII rules',
      layer: 'ui',
      kind: 'screen',
      summary: 'Governance redaction policy',
      constructs: 'Policy document with PII rules.',
      transmits: 'listPolicies + updatePolicy({pii}).',
      files: ['web/src/pages/PiiRules.tsx', 'shared/piiPolicy.ts'],
      apis: ['api.listPolicies', 'api.updatePolicy'],
      x: 520,
      y: 220,
    },
    {
      id: 'w-connections',
      label: 'Connections',
      layer: 'ui',
      kind: 'screen',
      summary: 'Env-scoped MCP / boards',
      constructs: 'Service catalog + OAuth/credentials forms.',
      transmits: 'connect/disconnect MCP; listEnvironments.',
      files: ['web/src/pages/Connections.tsx', 'web/src/lib/serviceCatalog.ts'],
      apis: ['api.listMcpConnections', 'api.connectMcp', 'api.disconnectMcp'],
      screenshotHint: 'Capture env switcher + connection row.',
      x: 520,
      y: 360,
    },
    {
      id: 'w-models',
      label: 'Models / Cloud',
      layer: 'ui',
      kind: 'screen',
      summary: 'Runtime preferences',
      constructs: 'Model prefs + cloud MCP bindings.',
      transmits: 'updatePolicy + health checks.',
      files: ['web/src/pages/Models.tsx', 'web/src/pages/Cloud.tsx'],
      apis: ['api.listPolicies', 'api.updatePolicy', 'api.health'],
      x: 520,
      y: 500,
    },
    {
      id: 'w-session',
      label: 'Web session',
      layer: 'client',
      kind: 'session',
      summary: 'localStorage demo session',
      constructs: 'Token + actor id/surface in browser storage.',
      transmits: 'Authorization Bearer + x-actor-* headers.',
      files: ['web/src/lib/session.ts'],
      x: 760,
      y: 140,
    },
    {
      id: 'w-shared-api',
      label: 'shared/api.ts',
      layer: 'client',
      kind: 'client',
      summary: 'Typed HTTP client',
      constructs: 'JSON bodies, query params, error mapping.',
      transmits: 'Vite proxy /api/v1 → backend :4000.',
      files: ['shared/api.ts', 'shared/types.ts'],
      x: 760,
      y: 320,
    },
    {
      id: 'w-env-cache',
      label: 'Env cache',
      layer: 'client',
      kind: 'client',
      summary: 'Active environment id',
      constructs: 'Cached env for connection scoping.',
      transmits: 'ACTIVE_ENV_CHANGED_EVENT to Home/Connections.',
      files: ['web/src/lib/environmentStorage.ts'],
      x: 760,
      y: 480,
    },
    {
      id: 'w-http',
      label: 'HTTP /api/v1',
      layer: 'api',
      kind: 'endpoint',
      summary: 'REST JSON only',
      constructs: 'No client WebSockets.',
      transmits: 'routes.ts handlers with auth middleware.',
      files: ['backend/src/routes.ts', 'backend/src/auth.ts'],
      x: 1000,
      y: 220,
    },
    {
      id: 'w-store',
      label: 'Store',
      layer: 'backend',
      kind: 'store',
      summary: 'In-memory source of truth',
      constructs: 'workItems, jobs, approvals, policies, mcp*.',
      transmits: 'Optional persist.ts → file/Postgres.',
      files: ['backend/src/store.ts', 'backend/src/persist.ts'],
      x: 1240,
      y: 140,
    },
    {
      id: 'w-orchestrator',
      label: 'Orchestrator',
      layer: 'runtime',
      kind: 'pipeline',
      summary: 'createJob + runJobPipeline',
      constructs: 'Job from triage decision + policy.',
      transmits: 'model runner + MCP gateway + board connector.',
      files: ['backend/src/orchestrator.ts'],
      apis: ['POST /work-items/:id/triage'],
      x: 1240,
      y: 320,
    },
    {
      id: 'w-model',
      label: 'Model runner',
      layer: 'runtime',
      kind: 'pipeline',
      summary: 'LLM / agent execution',
      constructs: 'Prompt + tools from policy + MCP.',
      transmits: 'Updates job status back into store.',
      files: ['backend/src/runners/model.ts', 'backend/src/mcp/'],
      x: 1240,
      y: 480,
    },
  ],
  edges: [
    { id: 'we1', from: 'w-login', to: 'w-session', label: 'token', primary: true },
    { id: 'we2', from: 'w-callback', to: 'w-session', label: 'exchange', primary: true },
    { id: 'we3', from: 'w-session', to: 'w-shared-api', label: 'Bearer', primary: true },
    { id: 'we4', from: 'w-workspace', to: 'w-onboarding', primary: true },
    { id: 'we5', from: 'w-onboarding', to: 'w-shared-api', label: 'putOnboarding' },
    { id: 'we6', from: 'w-home', to: 'w-shared-api', primary: true },
    { id: 'we7', from: 'w-triage', to: 'w-shared-api', label: 'triage', primary: true },
    { id: 'we8', from: 'w-work', to: 'w-shared-api' },
    { id: 'we9', from: 'w-task', to: 'w-shared-api' },
    { id: 'we10', from: 'w-approvals', to: 'w-shared-api' },
    { id: 'we11', from: 'w-pii', to: 'w-shared-api' },
    { id: 'we12', from: 'w-connections', to: 'w-shared-api', primary: true },
    { id: 'we13', from: 'w-connections', to: 'w-env-cache', label: 'env scope' },
    { id: 'we14', from: 'w-env-cache', to: 'w-home', label: 'widgets' },
    { id: 'we15', from: 'w-models', to: 'w-shared-api' },
    { id: 'we16', from: 'w-shared-api', to: 'w-http', primary: true },
    { id: 'we17', from: 'w-http', to: 'w-store', primary: true },
    { id: 'we18', from: 'w-http', to: 'w-orchestrator', label: 'aiFirst', primary: true },
    { id: 'we19', from: 'w-orchestrator', to: 'w-model', primary: true },
    { id: 'we20', from: 'w-model', to: 'w-store', label: 'job status', primary: true },
    { id: 'we21', from: 'w-triage', to: 'w-task', label: 'open item' },
    { id: 'we22', from: 'w-onboarding', to: 'w-home', primary: true },
    { id: 'we23', from: 'w-login', to: 'w-callback', label: 'federated' },
  ],
};
